version: "3.4"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: "scorder-backend"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "scorder-backend"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/var/lib/mysql